/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.programsmanagement.view;

import edu.programsmanagement.model.Program;
import edu.programsmanagement.dao.ProgramDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;

/**
 *
 * @author nbenayed
 */
public class ProgramGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProgramGUI
     */
    public ProgramGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelProgramCode = new javax.swing.JLabel();
        jLabelProgramTitle = new javax.swing.JLabel();
        jLabelAccreditation = new javax.swing.JLabel();
        jTextProgCode = new javax.swing.JTextField();
        jTextProgTitle = new javax.swing.JTextField();
        jTextAccreditation = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonAddProg = new javax.swing.JButton();
        jButtonUpdateProg = new javax.swing.JButton();
        jButtonDeleteProgram = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonShowAllPrograms = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAllPrograms = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Details");

        jLabelStatus.setForeground(new java.awt.Color(0, 0, 204));
        jLabelStatus.setText("jLabelStatus");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelProgramCode.setText("Program Code");

        jLabelProgramTitle.setText("Program Title");

        jLabelAccreditation.setText("Accreditation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAccreditation)
                            .addComponent(jLabelProgramTitle)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelProgramCode)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextProgCode, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jTextProgTitle)
                    .addComponent(jTextAccreditation, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProgramCode)
                    .addComponent(jTextProgCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextProgTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProgramTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAccreditation)
                    .addComponent(jTextAccreditation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAddProg.setText("Add Program");
        jButtonAddProg.setMaximumSize(new java.awt.Dimension(140, 29));
        jButtonAddProg.setMinimumSize(new java.awt.Dimension(140, 29));
        jButtonAddProg.setPreferredSize(new java.awt.Dimension(140, 29));
        jButtonAddProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProgActionPerformed(evt);
            }
        });

        jButtonUpdateProg.setText("Update Program");
        jButtonUpdateProg.setMaximumSize(new java.awt.Dimension(140, 29));
        jButtonUpdateProg.setMinimumSize(new java.awt.Dimension(140, 29));
        jButtonUpdateProg.setPreferredSize(new java.awt.Dimension(140, 29));
        jButtonUpdateProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateProgActionPerformed(evt);
            }
        });

        jButtonDeleteProgram.setText("Delete Program");
        jButtonDeleteProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAddProg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUpdateProg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDeleteProgram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteProgram)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonShowAllPrograms.setText("Show All Programs");
        jButtonShowAllPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllProgramsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonShowAllPrograms)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonShowAllPrograms)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jTableAllPrograms);

        jTableAllPrograms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAllPrograms);

        jScrollPane3.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProgActionPerformed
        // TODO add your handling code here:
        String code =jTextProgCode.getText().trim();
       String title=jTextProgTitle.getText().trim();
       String accreditation=jTextAccreditation.getText().trim();
      
       
       if (code.isEmpty() || title.isEmpty() || accreditation.isEmpty()){
           // display an error message
           jLabelStatus.setText("Please enter data");
           //exit the program
           return;
       }
       
        ProgramDAO programDAO=new ProgramDAO();
       //before adding the program, make sure that the code doesn't exist in the database
       
            try{
                if(programDAO.findProgramByCode(code) !=null){
                jLabelStatus.setText("Code exists in the DB");
                return;
                }
                
                //add a new program
                int insertStatus=programDAO.addNewProgram(code, title, accreditation);
                jLabelStatus.setText("Program "+code+" is added!");
                loadAllPrograms();
                
                }
        catch(SQLException e){
            jLabelStatus.setText(e.getMessage());
         
                }
      
    }//GEN-LAST:event_jButtonAddProgActionPerformed

    private void jButtonUpdateProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateProgActionPerformed
        // TODO add your handling code here:
        String code =jTextProgCode.getText().trim();
       String title=jTextProgTitle.getText().trim();
       String accreditation=jTextAccreditation.getText().trim();
      
       
       if (code.isEmpty() || title.isEmpty() || accreditation.isEmpty()){
           // display an error message
           jLabelStatus.setText("Please enter data");
           //exit the program
           return;
       }
       
        ProgramDAO programDAO=new ProgramDAO();
       //before adding the program, make sure that the code doesn't exist in the database
       
            int updateStatus=-1;
            try{
                if(programDAO.findProgramByCode(code) ==null){
                jLabelStatus.setText("Program does not exist in the DB");
                return;
                }
                Program program=new Program(code, title, accreditation);
              
                //update the employee
                updateStatus=programDAO.updateProgrampst(code, title, accreditation);

                if (updateStatus==1){
          jLabelStatus.setText("Program "+code+" is updated!");
          loadAllPrograms();
      }
      else {jLabelStatus.setText("No record is updated");}
                }
        catch(SQLException e){
            jLabelStatus.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateProgActionPerformed

    private void jButtonDeleteProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProgramActionPerformed
        // TODO add your handling code here:
         String code=jTextProgCode.getText().trim();
        //check if empid is empty 
        if(code.isEmpty()){
            jLabelStatus.setText("Please enter the code of the program to delete");
            return;
        }
        ProgramDAO programDAO=new ProgramDAO();
        int deleteStatus=-1;
        try{
            if(programDAO.findProgramByCode(code)==null){
                jLabelStatus.setText("Program Code does not exist in the DB");
                return;

            }
            deleteStatus=programDAO.deleteProgram(code);
        }
        catch (SQLException e){
            jLabelStatus.setText(e.getMessage());
        }
        if(deleteStatus==1){
            jLabelStatus.setText("Program "+code+" is deleted!");
            jTextProgCode.setText(" ");
            jTextProgTitle.setText(" ");
            jTextAccreditation.setText(" ");
            loadAllPrograms();
        }
        else{
            jLabelStatus.setText("Error while deleting "+code+"program");
        }
        
    }//GEN-LAST:event_jButtonDeleteProgramActionPerformed

    private void jButtonShowAllProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllProgramsActionPerformed
        loadAllPrograms();
    }//GEN-LAST:event_jButtonShowAllProgramsActionPerformed
    private void loadAllPrograms(){
        //step 1:  set the column name of the jtable
        Vector colNameV=new Vector();
        colNameV.add("Program Code");
        colNameV.add("Program Title");
        colNameV.add("Accreditation");
        
       
        
        //Step 2: set the rows of jtable
        
        //2.a retreive all program data
        ProgramDAO programDAO=new ProgramDAO();
        List<Program> programList=null;
        try{
            programList=programDAO.getAllPrograms();
        }
        catch(SQLException e){
            jLabelStatus.setText("Database Error! "+e.getMessage());
         
        }
        
        //convert the programList and data in it to a vector of vectors
        Vector rowDataVector = new Vector();
        Vector cellVector = null;

        for (Program p:programList){
            cellVector=new Vector();
            cellVector.add(p.getCode());
            cellVector.add(p.getTitle());
            cellVector.add(p.getAccreditation());
           //add this cell data vector to the rowDataVector
        rowDataVector.add(cellVector);
        }
        
        
        //init the JTable instance using the row data and column data vectors
        jTableAllPrograms=new JTable(rowDataVector,colNameV);
        jScrollPane3.setViewportView(jTableAllPrograms);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddProg;
    private javax.swing.JButton jButtonDeleteProgram;
    private javax.swing.JButton jButtonShowAllPrograms;
    private javax.swing.JButton jButtonUpdateProg;
    private javax.swing.JLabel jLabelAccreditation;
    private javax.swing.JLabel jLabelProgramCode;
    private javax.swing.JLabel jLabelProgramTitle;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAllPrograms;
    private javax.swing.JTextField jTextAccreditation;
    private javax.swing.JTextField jTextProgCode;
    private javax.swing.JTextField jTextProgTitle;
    // End of variables declaration//GEN-END:variables
}
